name: deploy
on:
  workflow_dispatch:
    inputs:
      note:
        default: 'Deploy by github action'
      env:
        default: 'gke-prod'
        type: choice
        options:
          - gke-prod

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HARBOR_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: build-push-docker-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT }}:${{ github.sha }}

  deploy_gke:
    runs-on: ubuntu-latest
    env:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      IMAGE_TAG: ${{ github.sha }}
      HARBOR_HOST: ${{ vars.HARBOR_HOST }}
      K8S_REPO: ${{ vars.K8S_REPO }}
    needs:
      - dockerize
    steps:
      - name: deploy k8s by argocd
        run: |
          git config --global user.email "GitOps@sota-labs.com"
          git config --global user.name "GitOps"
          git clone --branch main https://GitOps:$CICD_TOKEN@$K8S_REPO manifest
          cd manifest
          sed -i "s15|newTag:.*|newTag: ${{ env.IMAGE_TAG}}|g" ./applications/api/overlays/${{ inputs.env }}/kustomization.yaml
          git add  ./applications/api/overlays/${{ inputs.env }}/kustomization.yaml
          git commit -m "GitOps deploy image ${{ env.IMAGE_TAG }} to personal-agents ${{ env.ENV }}"
          git push
